spring:
  profiles:
    active: dev
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yincn/microservice-springcloud-config-readconfig.git #GitHub上面的git仓库名字，要根据 HTTPS/SSH 二选 一，SSH需要配置公私密钥
          username: yincn
          password: ***
          
server: 
  port: 3344 
         
eureka:
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/
  instance: 
    instance-id: config-01
    prefer-ip-address: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
          
logging:
  config: classpath:logback-boot.xml
  path: /project/logs/microservice-springcloud/config