spring: 
  profiles:
    active: dev
  application:
    name: consumer
  
server:
  port: 8088
            
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
eureka:
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/
  instance: 
    instance-id: consumer-01
    prefer-ip-address: true
  
logging:
  config: classpath:logback-boot.xml